_wandb:
    value:
        cli_version: 0.16.3
        python_version: 3.9.13
        t:
            1:
                - 55
            2:
                - 55
            3:
                - 13
                - 23
            4: 3.9.13
            5: 0.16.3
            8:
                - 5
            12: 0.17.0b9
            13: darwin-x86_64
