wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709077771.495355
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.12.2
      5: 0.16.3
      8:
      - 5
      13: darwin-x86_64
